runtime: python310

handlers:
  - url: /css
    static_dir: css
    mime_type: text/css

  - url: /scripts
    static_dir: scripts
    mime_type: application/javascript

  - public: /public
    static_dir: public

  - url: /.*
    static_file: index.html
    upload: index.html
